# Generated by Django 5.2.7 on 2025-10-30 14:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('image', models.FileField(upload_to='images/sup_category')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SuperCategory',
                'verbose_name_plural': 'SuperCategroies',
                'db_table': 'super_category',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('flag', models.FileField(upload_to='images/country')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('image', models.FileField(upload_to='images/services')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desc', models.TextField()),
                ('main_image', models.FileField(upload_to='images/product')),
                ('color', models.CharField(choices=[('aliceblue', 'AliceBlue'), ('antiquewhite', 'AntiqueWhite'), ('aqua', 'Aqua'), ('aquamarine', 'Aquamarine'), ('azure', 'Azure'), ('beige', 'Beige'), ('bisque', 'Bisque'), ('black', 'Black'), ('blanchedalmond', 'BlanchedAlmond'), ('blue', 'Blue'), ('blueviolet', 'BlueViolet'), ('brown', 'Brown'), ('burlywood', 'BurlyWood'), ('cadetblue', 'CadetBlue'), ('chartreuse', 'Chartreuse'), ('chocolate', 'Chocolate'), ('coral', 'Coral'), ('cornflowerblue', 'CornflowerBlue'), ('cornsilk', 'Cornsilk'), ('crimson', 'Crimson'), ('cyan', 'Cyan'), ('darkblue', 'DarkBlue'), ('darkcyan', 'DarkCyan'), ('darkgoldenrod', 'DarkGoldenRod'), ('darkgray', 'DarkGray'), ('darkgreen', 'DarkGreen'), ('darkkhaki', 'DarkKhaki'), ('darkmagenta', 'DarkMagenta'), ('darkolivegreen', 'DarkOliveGreen'), ('darkorange', 'DarkOrange'), ('darkorchid', 'DarkOrchid'), ('darkred', 'DarkRed'), ('darksalmon', 'DarkSalmon'), ('darkseagreen', 'DarkSeaGreen'), ('darkslateblue', 'DarkSlateBlue'), ('darkslategray', 'DarkSlateGray'), ('darkturquoise', 'DarkTurquoise'), ('darkviolet', 'DarkViolet'), ('deeppink', 'DeepPink'), ('deepskyblue', 'DeepSkyBlue'), ('dimgray', 'DimGray'), ('dodgerblue', 'DodgerBlue'), ('firebrick', 'FireBrick'), ('floralwhite', 'FloralWhite'), ('forestgreen', 'ForestGreen'), ('fuchsia', 'Fuchsia'), ('gainsboro', 'Gainsboro'), ('ghostwhite', 'GhostWhite'), ('gold', 'Gold'), ('goldenrod', 'GoldenRod'), ('gray', 'Gray'), ('green', 'Green')], default='gold', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('guarantee', models.PositiveSmallIntegerField(default=1)),
                ('delivery_time', models.CharField(choices=[('1-3', '1-3'), ('3-5', '3-5'), ('5-15', '5-15')], default='1-3', max_length=50)),
                ('review', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Middle'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=50, null=True)),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('recomended', models.BooleanField(default=False)),
                ('company', models.CharField(max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.country')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='images/product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='images/sub_category')),
                ('color', models.CharField(choices=[('aliceblue', 'AliceBlue'), ('antiquewhite', 'AntiqueWhite'), ('aqua', 'Aqua'), ('aquamarine', 'Aquamarine'), ('azure', 'Azure'), ('beige', 'Beige'), ('bisque', 'Bisque'), ('black', 'Black'), ('blanchedalmond', 'BlanchedAlmond'), ('blue', 'Blue'), ('blueviolet', 'BlueViolet'), ('brown', 'Brown'), ('burlywood', 'BurlyWood'), ('cadetblue', 'CadetBlue'), ('chartreuse', 'Chartreuse'), ('chocolate', 'Chocolate'), ('coral', 'Coral'), ('cornflowerblue', 'CornflowerBlue'), ('cornsilk', 'Cornsilk'), ('crimson', 'Crimson'), ('cyan', 'Cyan'), ('darkblue', 'DarkBlue'), ('darkcyan', 'DarkCyan'), ('darkgoldenrod', 'DarkGoldenRod'), ('darkgray', 'DarkGray'), ('darkgreen', 'DarkGreen'), ('darkkhaki', 'DarkKhaki'), ('darkmagenta', 'DarkMagenta'), ('darkolivegreen', 'DarkOliveGreen'), ('darkorange', 'DarkOrange'), ('darkorchid', 'DarkOrchid'), ('darkred', 'DarkRed'), ('darksalmon', 'DarkSalmon'), ('darkseagreen', 'DarkSeaGreen'), ('darkslateblue', 'DarkSlateBlue'), ('darkslategray', 'DarkSlateGray'), ('darkturquoise', 'DarkTurquoise'), ('darkviolet', 'DarkViolet'), ('deeppink', 'DeepPink'), ('deepskyblue', 'DeepSkyBlue'), ('dimgray', 'DimGray'), ('dodgerblue', 'DodgerBlue'), ('firebrick', 'FireBrick'), ('floralwhite', 'FloralWhite'), ('forestgreen', 'ForestGreen'), ('fuchsia', 'Fuchsia'), ('gainsboro', 'Gainsboro'), ('ghostwhite', 'GhostWhite'), ('gold', 'Gold'), ('goldenrod', 'GoldenRod'), ('gray', 'Gray'), ('green', 'Green')], default='green', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='main.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategroies',
                'db_table': 'sub_category',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.subcategory'),
        ),
    ]
